exclude: '\.snap$'
repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        language_version: python3.11
  - repo: local
    hooks:
    - id: pytest-check
      name: pytest-check
      stages: [push]
      types: [python]
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
