[tool.poetry]
name = "Sous-titreur"
version = "0.0.1"
description = "Sous-titrer des interviews grâce à Whisper d'OpenAI"
authors = ["jissagn <7462969+jissagn@users.noreply.github.com>"]


[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.89.1"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
celery = {extras = ["pytest"], version = "^5.2.7"}
redis = "^4.5.1"
requests = "^2.28.2"
sqlalchemy = "^2.0.4"
psycopg2-binary = "^2.9.5"
python-multipart = "^0.0.6"
llvmlite = "0.40.0rc1"
numba = "0.57.0rc1"
openai-whisper = "^20230314"
structlog = "^23.1.0"
simplejson = "^3.19.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
pre-commit = "^2.20.0"
pytest = "^7.1.3"

[tool.poetry.group.dev.dependencies]
httpx = "^0.23.3"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | \.github
  | \.venv
  | \.vscode
  | build
  | dist
)/
'''


[tool.isort]
profile = 'black'

[tool.flake8]
max-line-length = 130

[build-system]
requires = ["poetry>=1.3.2", "pip>=22.3.1"]
build-backend = "poetry.masonry.api"
